# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :firebase do
    firebase_app_distribution(
      app: "1:569892023598:android:3953d49865cefc345b1ebf",
      android_artifact_type: "AAB",
      android_artifact_path: "../build/app/outputs/bundle/release/app-release.aab",
      groups: "testers",
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    sh "flutter clean"
    sh "flutter build appbundle"
    upload_to_play_store(
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      track: "internal",
    )
  end
end
